export const styles = {
  container: {
    width: "100%",
    minHeight: 960,
    backgroundColor: "#fcfcfc",
    position: "relative",
  },
  header: {
    width: "100%",
    height: 64,
    backgroundColor: "#fcfcfc",
    borderBottom: "1px solid rgba(26, 27, 28, 0.1)",
  },
  headerContent: {
    maxWidth: 1920,
    height: "100%",
    margin: "0 auto",
    display: "flex",
    alignItems: "center",
    padding: "0 32px",
    position: "relative",
  },
  logo: {
    fontFamily: "Roobert TRIAL",
    fontSize: 14,
    fontWeight: 600,
    letterSpacing: -0.28,
    textTransform: "uppercase",
    lineHeight: "16px",
    color: "#1a1b1c",
  },
  location: {
    marginLeft: 85,
    opacity: 0.6,
  },
  locationFrame: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  rectangle: {
    width: 4,
    height: 17,
    borderRadius: 2,
    border: "1px solid #1a1b1c",
  },
  introText: {
    fontFamily: "Roobert TRIAL",
    fontSize: 14,
    fontWeight: 600,
    letterSpacing: -0.28,
    textTransform: "uppercase",
    lineHeight: "16px",
    color: "#1a1b1c",
  },
  takeTestButton: {
    position: "absolute",
    right: 32,
    padding: "8px 16px",
    backgroundColor: "#1a1b1c",
    border: "none",
    cursor: "pointer",
  },
  buttonText: {
    fontFamily: "Roobert TRIAL",
    fontSize: 10,
    fontWeight: 600,
    letterSpacing: -0.2,
    textTransform: "uppercase",
    lineHeight: "16px",
    color: "#fcfcfc",
  },
  analysisTitle: {
    fontFamily: "Roobert TRIAL",
    fontSize: 16,
    fontWeight: 600,
    letterSpacing: -0.32,
    textTransform: "uppercase",
    lineHeight: "24px",
    color: "#1a1b1c",
    margin: "86px 0 0 32px",
  },
  optionsContainer: {
    display: "flex",
    gap: 32,
    padding: "40px 32px",
  },
  optionCard: {
    width: 481,
    height: 481,
    position: "relative",
    backgroundColor: "#d9d9d9",
  },
  rhombusBackground: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
  },
  rhombusImage: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  cardContent: {
    position: "relative",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    height: "100%",
  },
  iconImage: {
    width: 136,
    height: 136,
    marginBottom: 20,
  },
  titleGroup: {
    display: "flex",
    alignItems: "center",
    gap: 10,
  },
  groupIcon: {
    width: 66,
    height: 59,
  },
  cardText: {
    fontFamily: "Roobert TRIAL",
    fontSize: 14,
    fontWeight: 400,
    textTransform: "uppercase",
    lineHeight: "24px",
    color: "#1a1b1c",
    margin: 0,
  },
  backButton: {
    display: "flex",
    alignItems: "center",
    gap: 16,
    margin: "32px",
    cursor: "pointer",
  },
  backIcon: {
    width: 44,
    height: 44,
  },
  backText: {
    fontFamily: "Roobert TRIAL",
    fontSize: 14,
    fontWeight: 600,
    letterSpacing: -0.28,
    textTransform: "uppercase",
    lineHeight: "16px",
    color: "#1a1b1c",
    opacity: 0.7,
  },
};
